// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upgrade_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateToChirpyRed = `-- name: UpdateToChirpyRed :exec
UPDATE users
SET is_chirpy_red=TRUE
WHERE id=$1
`

func (q *Queries) UpdateToChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateToChirpyRed, id)
	return err
}
